### ISSUE TITLE
Special letters create multiple titles

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Reference#2]
I have a list of names, some start with É or OE.

Reference creates multiple titles for these special letters.

See:

![screenshot-2018-6-14 contenus afas](https://user-images.githubusercontent.com/5262986/41426397-c3a2a104-7003-11e8-873a-2a0d9a3cfe37.png)

Or:

![screenshot-2018-6-14 contenus afas 1](https://user-images.githubusercontent.com/5262986/41426405-c7ddb0ba-7003-11e8-8632-19f16cb30907.png)

**Comment by Daniel-KM** [comment]
Ok. I 'll fix it in a few days.

**Comment by pprw** [comment]
Thanks. On the same subject, I think É should be just after E in the alphabetical heading. The same for OE just after O.

**Comment by Daniel-KM** [comment]
I this is fixed in last version (3.4.10). Note that this is a complex subject, and that the order may vary between people and soft. I try to use the order provided by mariadb (mysql), that follows the standard unicode, but php follows the standard unicode too, but some detais are different in a default config. 
So the new version fixes the issue above, except for the Œ in some cases. 
Like in the dictionnary, the diacritic are ordered with the main letter. 
To fixes all issues, the initial letter should be get via sql, but the `convert `command is not manageable directly by Doctrine, so you can fix it: see https://github.com/Daniel-KM/Omeka-S-module-Reference/blob/master/src/Mvc/Controller/Plugin/Reference.php#L685.

**Comment by pprw** [comment]
I tested the last git version and I can confirm it fixes the problem for E É but not for O OE.

**Comment by pprw** [comment]
I cloned my Omeka S installation to another server and I have this bug (with É and E) appears again.

The bug does not appear on the old server:
![old server](https://user-images.githubusercontent.com/5262986/45264851-4ea45080-b443-11e8-93a8-04cc2192c7bc.png)


But it appears on this new one:

![new server](https://user-images.githubusercontent.com/5262986/45264855-5a901280-b443-11e8-9d15-79784e24c10c.png)

Is there something I can do?

**Comment by Daniel-KM** [comment]
Do you have the same version of Reference ?

**Comment by pprw** [comment]
Yes, it is the exact same omeka S installation+modules+themes (just a clone) with the same database (also a clone).

**Comment by Daniel-KM** [comment]
I have no idea, the module uses mbstring or iconv, and you have them. Anyway the initial is extracted directly from the database, so it's probably related to the database. To be sure, try to purge your database, uninstall mariadb, then install mysql, then import the database. Anyway, I use mariadb, that is the default in main distribution now, without error (except for Œ). If this is an automatic virtual machine (vagrant), i can check, else it will be hard to find.

**Comment by Daniel-KM** [comment]
You find the best solution!

**Comment by pprw** [comment]
I just re-experienced this bug with Omeka 3.0 and Reference (master)

New fact : Some accented letters are correctly under "E", some other not. See "Éthique artificielle".

![image](https://user-images.githubusercontent.com/5262986/99051005-8fa2cd00-2598-11eb-8885-bcde6b2ac299.png)
![image](https://user-images.githubusercontent.com/5262986/99051384-ae08c880-2598-11eb-929f-ada61cc6a436.png)

**Comment by pprw** [comment]
up :-)

**Comment by Daniel-KM** [comment]
Les cas différents sont peut-être liés à des espaces dans les sujets ?

**Comment by Daniel-KM** [comment]
C'est peut-être lié ua thème. Qu'est-ce que cela donne avec le thème par défaut ?

**Comment by pprw** [comment]
> C'est peut-être lié ua thème. Qu'est-ce que cela donne avec le thème par défaut ?

Je viens de tester : même problème.

**Comment by mufticsanjin** [comment]
I might have a similar issue related to this thread happening on this page: [https://ibali.uct.ac.za/s/bvf41/page/people 1](https://ibali.uct.ac.za/s/bvf41/page/people). Apologies for cross posting on the omeka forum as well...

If you click on the [0-9 heading](https://ibali.uct.ac.za/s/bvf41/page/people#0-9) it takes you down where you will see a lot of names that begin with special characters. So they are grouped correctly. However, what we would like is to have this appear at the top of the page, and to change the label 0-9 to be basically one of each of the special characters:

ǀ ǁ ǂ ǃ

Now the thing is that we recently upgraded to Omeka 3.2.3 from 3.2.1 and I could almost promise that we had it exactly how we wanted - the heading at the top bar and in the body was created out of the first characters (instead of 0-9), and they were the first thing on the list. We had also recently upgraded the OS on our server as well.

Is there something we could change in the common/reference.phtml code to make this happen? Is it something that was happening in an earlier version of the Reference module?

**Comment by mufticsanjin** [comment]
We had an issue similar to this, but happening with special characters that we posted on the [Omeka Forum](https://forum.omeka.org/t/reference-module-headings-with-special-characters/23335/3). We discovered that in a server os upgrade we did not install the php extension [intl](https://www.php.net/manual/en/book.intl.php) and once we got it working, we could get the headings to recognize the special characters and group the items properly.
